DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rides CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS destination CASCADE;
DROP TABLE IF EXISTS destinations CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS users_rides CASCADE;
